### ISSUE TITLE
Deployment Issues

### ISSUE THREAD

**Issue by udragon** [kwk/docker-registry-frontend#102]
I tried to deploy the registry and the frontend v2, without success. Here is what I did:

docker run \
  -d \
  -p 5000:5000 \
  -v /etc/pki/tls/certs:/certs \
  -v /storage:/var/lib/registry \
  -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/localhost.crt \
  -e REGISTRY_HTTP_TLS_KEY=/certs/localhost.key \
  --name docker-registry \
  registry:2

docker run \
  -d \
  -e ENV_DOCKER_REGISTRY_HOST=localhost \
  -e ENV_DOCKER_REGISTRY_PORT=5000 \
  -e ENV_DOCKER_REGISTRY_USE_SSL=1 \
  -e ENV_USE_SSL=yes \
  -p 80:80 \
  -p 443:443 \
  -v /etc/pki/tls/certs/localhost.crt:/etc/apache2/server.crt:ro \
  -v /etc/pki/tls/certs/localhost.key:/etc/apache2/server.key:ro \
  konradkleine/docker-registry-frontend:v2

https://localhost:5000/v2 works fine;
https://localhost/v2/ Returns service unavailable.
https://localhost/repositories don't seem to get any.
Without the SSL I've got similar results.

**Comment by pachiras** [comment]
In my case, after pressing "Browse repositories" button, I couldn't get no
response. Below is my settings:

docker run -d -p 5050:5000 --restart=always -v /var/registry:/tmp/registry --name registry registry:2

docker run \
  -d \
  -e ENV_DOCKER_REGISTRY_HOST=localhost \
  -e ENV_DOCKER_REGISTRY_PORT=5050 \
  -p 5080:80 \
  --name registry-frontend \
  konradkleine/docker-registry-frontend:v2

![dockerfe](https://cloud.githubusercontent.com/assets/13953741/13240634/7b39c952-da27-11e5-8259-ba37bf4f7a16.png)

The server seems to be trying to access port 5080 to get the repository list instead of 5050 where docker registry container runs.

Am I doing wrong?
Thanks.

**Comment by kwk** [comment]
Please see the [example-setup](https://github.com/kwk/docker-registry-frontend/tree/v2/example-setup)  folder in the souce for a working setup and start from there. I'm sorry but I cannot support every setup request coming in here as a bug. 

@pachiras The localhost:5080 proxies the call to the registry on 5050. It's done in the apache config.
