### ISSUE TITLE
I'ts not possible to push to repository

### ISSUE THREAD

**Issue by scibi** [kwk/docker-registry-frontend#120]
Currently browse only mode is forced in `start-apache.sh`

``` bash
# Overwrite browse-only option for now since only browse-only is working right now
ENV_MODE_BROWSE_ONLY=true
```

It makes proxy useless because I'm not able tu push anything to the repo. Running:

```
docker push server.fqdn/debian
```

ends with Apache error:

```
frontend_1 | [Tue Apr 12 10:07:39.464234 2016] [access_compat:error] [pid 49:tid 139738640021248] [client CLIENT_IP:54766] AH01797: client denied by server configuration: proxy:https://registry:5000/v2/debian/blobs/uploads/
```

I've tested it with example setup (I replaced certificates to match server fqdn).

**Comment by kwk** [comment]
Don't mix the front-end's browse-only-mode with the actual registry. The frontend doesn't affect what you can do with your registry. Also, please use the issue template next time you open an issue. Thank you.

**Comment by krobertson** [comment]
@kwk I ran into this today and I believe you might have misunderstood the ticket.

Currently, browse-only-mode is _force_, so it does affect what you can do with your repository when the repository is behind the front end. From the readme, it seemed as though this configuration should work since it isn't called out.
