### ISSUE TITLE
Is this dead?

### ISSUE THREAD

**Issue by manuelmazzuola** [kwk/docker-registry-frontend#125]
@kwk if you need help please add someone to the team of this project that can help you to review PRs and merge them.

**Comment by justjoheinz** [comment]
+1 - it is a nice project!

**Comment by 0x46616c6b** [comment]
+1

**Comment by kwk** [comment]
@manuelmazzuola no, this project is not dead but I'm overwhelmed by the number of recent contributions. We need more automated tests for the whole project that ensure we don't break things. I currently have to do too much testing by hand to ensure a certain level of stability. Please excuse, that it takes a long time to get PRs pulled in.

Making someone a team member is hard because not everybody who contributes, does test their changes in all hidden corners. No offence.

@justjoheinz thanks

**Comment by manuelmazzuola** [comment]
Choose wisely and make someone help you
