### ISSUE TITLE
npm build fails on travis-ci.org

### ISSUE THREAD

**Issue by goern** [kwk/docker-registry-frontend#35]
I set up a CI job at travis, it fails, pls see https://travis-ci.org/goern/docker-registry-frontend

**Comment by kwk** [comment]
Hi Christoph, it's nice to see you using this project. You got me ;) When I started this project I used yeoman and left the test stub files in the project. I never wrote any tests for the project but I would love to see other people like you commit some. This project was born out of the need for a company internal tool but seems to be adopted by the community pretty well if you look at the almost 30k pulls from docker hub.

Anyways, the projects seems to be reasonably stable and bullet proof regarding the number of issues reported. The V1 Registry API is almost fully covered (only missing put and pull of layer data). With the advent of docker distribution (https://github.com/docker/distribution) and the Registry 2.0 implementation I think it makes sense to focus on it because the Registry V1.0 is somewhat limited.

If I were to develop another project against some defined API I would definitively start with tests.

**Comment by goern** [comment]
Ja, fully agree, focus on registry v2 ;) 
Regarding the tests.. I am happy to remove them from my fork, any way to make test lights a bright green bulb is a good way... :P 

As you may have noticed I forked and ported the docker-registry-frontend to CentOS7 and I am moving forward to make it a OpenShift3 service that talks to the OS3 registry... stay tuned.
