### ISSUE TITLE
Support for Docker Registry 2.0

### ISSUE THREAD

**Issue by joberget** [kwk/docker-registry-frontend#43]
Hi, Docker released Registry 2.0 which supersedes https://github.com/docker/docker-registry. I hope this project will support it.

Registry 2.0
https://github.com/docker/distribution

**Comment by kwk** [comment]
Yes, there are plans in the making.

**Comment by joberget** [comment]
Great to hear!

**Comment by HeadlessChild** [comment]
I'm pleased to hear. :+1:

**Comment by kwk** [comment]
We need to have the search API implemented in the docker registry itself. Also,  docker/distribution/pull/173 needs to be implemented to have a tagging API.

**Comment by AngryHacker** [comment]
@kwk  Great to hear that you plan to support registry V2. 

May I ask when it will be available? Or it just depends on the two APIs needed to be implemented by docker/distribution -- In other word, it may cost a long period?

**Comment by kwk** [comment]
@AngryHacker 

> May I ask when it will be available?

I hope we have a first version by the end of July. I suggest we collect features that shall be in it including those that we already have in the current frontend. One issue for each feature would be perfect (e.g. starting with the basic "Show all repositories", "List images inside a repository") and then label each issue with **Feature planned for Docker Registry API v2 support**.

> Or it just depends on the two APIs needed to be implemented by docker/distribution -- In other word, it may cost a long period?

No, I it does not depend on these.

**Comment by kwk** [comment]
I've also created a milestone for this task. Feel free to open features you'd like to see in an early or later version of the frontend and I'll assign them the correct label and add them to the milestone.

**Comment by AngryHacker** [comment]
@kwk It seems that the two APIs is not available in distribution. Is it a trouble to implement API v2 support?

**Comment by kikicarbonell** [comment]
I'm pleased to hear. :+1:

**Comment by catuss-a** [comment]
+1, waiting the api v2 support!

**Comment by mike227** [comment]
+1

**Comment by kwk** [comment]
# Progress update

First and foremost, thank you for your support, for demanding new features, and for reporting bugs! I feel really proud with the **docker-registry-frontend being pulled over 200.000 times** from the [Docker Hub](https://registry.hub.docker.com/u/konradkleine/docker-registry-frontend/).

*Be warned, supporting the V2 API isn't just a matter of exchanging the API endpoint from `/v1/` to `/v2/`!*

I have thought about various ideas and experimented with many (new) technologies that are currently not used by the docker-registry-frontend. My ideas about the new frontend are more and more evolving and at the moment I have this stack of containers in mind that make up the new docker-registry-frontend. They can be composed in a single `docker-compose.yml` for a simple installation.

*Please be aware, that this is the most simply setup and that it can scale once one introduces more than one registry.*

## Architecture

### Registry

This is the registry v2 container.

There's not much configuration needed here except it must be configured to send [notifications](https://docs.docker.com/registry/notifications/) to at least one endpoint. In the most simple case, these notifications are directly consumed by [logstash](#logstash).

### Logstash

If you don't know [logstash](https://www.elastic.co/products/logstash) yet, consider it as a solution to take input data from [almost any source](https://www.elastic.co/guide/en/logstash/current/input-plugins.html), transform it (optional), and output the augmented or transformed input data to [almost any data sink](https://www.elastic.co/guide/en/logstash/current/output-plugins.html).

The **logstash** container is supposed to consume, transform and forward notifications  [notifications](https://docs.docker.com/registry/notifications/) generated by the [docker registry](#Registry) container.

As a consumer it must have an [`http` input](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-http.html) that accepts the notifications from the registry.

That's fairly easy to accomplish actually and doesn't take more than these few lines of code in the `logstash.conf`:

```
input
{ 
  # For information about http input see
  # https://www.elastic.co/guide/en/logstash/current/plugins-inputs-http.html
  http {
    host => "0.0.0.0"
    port => 8080
    ssl => false
    tags => [
      "docker",
      "registry",
      "event",
      "notification"
    ]
  }
}
```

#### Transforming and augmenting inputs

The input data generated by the [docker registry](#Registry) is JSON formatted and documented fairly well.

My biggest complaint about the Docker Registry API v2 is that they have removed the `/search` endpoint which could list all namespaces in your registry. To overcome this missing endpoint with the *notifications* they've added to the API, I'm thinking to transform the notifications that hit **logstash** as inputs into documents of a MongoDB database. (*Why Mongo? Please, read until the end of this update!*).

## docker-registry-frontend

Over that last few weeks I've played with and evaluated several cool technologies. It wasn't for fun but for actual internal projects and also to handle the limited amount of things you can do with the current docker-registry-frontend.

In its current state the docker-registry-frontend gets all its information from the docker registry through the V1 API endpoints. There's no database involved, only an Apache that handles authentication, SSL, and forwarding of HTTP requests to the registry.

In that sense, the docker-registry-frontend knows no state and is only reflecting a registry through the HTTP API. That's all nice and dandy but I want more and it seems that people are also demanding more. There have been some requests for *authorization* and more *authentication* backends.

I'll give my best to maintain the current docker-registry-frontend (the one that targets V1) for as long as I can. But I think I must take one step back to really support the new V2 registry. The new docker-registry-frontend (as I'm seeing it now) will be a whole lot different and a lot more modular. To follow the docker terminology: I will try to *include batteries* but you might need to recharge or replace them to fit your needs :)

### Meteor

I've been a huge fan of [Meteor](https://www.meteor.com/) for quite some time. It is basically a client/server stack built on [NodeJS](https://nodejs.org/) with JavaScript on both ends and a [Mongo database](http://www.mongodb.org) as well. It has so many neat features that I don't want to list all here.

#### Realtime events

The [logstash](#logstash) can have more than one `output { }` section or *data sinks*. I think about configuring a [websocket output](https://www.elastic.co/guide/en/logstash/current/plugins-outputs-websocket.html) to which the docker-registry-frontend can connect and show live data of what's happending on your registry, e.g. *tag XY created*, *image pushed* **without a reload**.

### AngularJS and Bootstrap

On top of meteor the UI will probably again be written with AngularJS and Bootstrap. I know both and feel very comfortable. If you prefer Google's Material Design, feel free to drop a note here but also give me good reasons to consider the one over the other and please **do not start bashing around**.

### MongoDB

Like I've mentioned in the [Meteor](#Meteor) section, meteor ships with MongoDB. I will ship it as it's own container though. Then Meteor can use it as datastorage. Most likely the [logstash](#logstash) will output it's transformed notifications to this MongoDB instance. Then the meteor application "knows" about existing repositories/namespaces and we can show them in the UI. Then we also have back our old and beloved repository list.

*For sure, one thing to consider when relying on notifications is what happens if notifications cannot be delivered or if you already have images stored in your registry. For the first problem, one maybe can setup a [Kafka](http://kafka.apache.org/) cluster to **decouple** the *consumer* (here: [logstash](#logstash)) from the *producer* (here: [docker registry](#registry)).*

# Summary

All in all we have these containers to wire up and create or simply use and configure:

* registry
* logstash
* mongodb
* docker-registry-frontend

If you want to monitor your docker registry you can also make use of additional containers that I'm going to provide. I'm thinking about elasticsearch or influxdb with Kibana or Graphana frontends. To *feed* these frontends one simply needs to add another `output { }` section to the `logstash.conf` file.

I hope you like my ideas so far. I look forward for your feedback!

Now, back to work.

**Comment by jgangemi** [comment]
not sure if you've seen this but there are plans to include some kind of catalog api to the registry that would eliminate the need to listen for webhooks: https://github.com/docker/distribution/pull/583

**Comment by jonatanblue** [comment]
Great to hear your plans for v2.

> the docker-registry-frontend knows no state and is only reflecting a registry through the HTTP API

Is this a bad thing though?

Also looks like the API updates @jgangemi mentioned are happening https://github.com/docker/distribution/pull/653

**Comment by bateau84** [comment]
+1

**Comment by deimosfr** [comment]
+1

**Comment by jose-delarosa** [comment]
Any current issues with v2.0? I pull the image, run it as instructed (specifying registry host and port), no SSL, no Kerberos, nothing fancy but when I go to the web ui (great look by the way) I do NOT see my registry.

**Comment by jonatanblue** [comment]
@jose-delarosa this issue still being open suggests that there is still no support for v2

**Comment by jose-delarosa** [comment]
@jonatanblue, yes that makes sense and the Docker Hub page makes it clear it is still under heavy development. I appreciate all the work everyone here does, I am but a humble user of your great work.

**Comment by bchanan03** [comment]
hi all,
any progress here? on registry v2.1.1 - according to Docker registry API should work

**Comment by kwk** [comment]
@bchanan03 Can you elaborate on that? You can try running the `docker-registry-frontend:v2` tag. It is a temporal solution with much less features than before but it should list repos and tags fine. I use it myself.

**Comment by bchanan03** [comment]
Hi 
(Please note this is a copy of respone on bug #66)
I have same problem - am using docker registry v2.1.1 and here is the yaml file:
http://pastebin.com/XTjfWYTJ
As my docker registry is new - I was able to push localhost:5000/busybox into it
Also I was able to pull the image - but the UI still shows empty list of images on my repository

Here is how I started docker registry:
/usr/bin/docker run -d -p 5000:5000 -v /home/core/trust_authority/containers//secure-registry/config.yml:/go/src/github.com/docker/distribution/cmd/registry/config.yml -e SEARCH_BACKEND=sqlalchemy -e SQLALCHEMY_INDEX_DATABASE=sqlite:////tmp/docker-registry.db --name secure-registry registry:2.1.1

Here is how I started docker registry UI v2:
docker run -d -e ENV_DOCKER_REGISTRY_HOST=localhost -e ENV_DOCKER_REGISTRY_HOST=5000 -p 8080:80 konradkleine/docker-registry-frontend:v2

**Comment by kwk** [comment]
I've locked this issue because it is too vague. There are other issues that also deal with v2 support but are much more differentiated.
