### ISSUE TITLE
failed to Delete images in the registry INTERNAL SERVER ERROR

### ISSUE THREAD

**Issue by vchedeti** [kwk/docker-registry-frontend#45]
when I try to delete images from the UI it gives INTERNAL SERVER ERROR

**Comment by vchedeti** [comment]
pull, push and search were working. But DELETE is not working . I tried curl DELETE from terminal, this is also not working. I had same issue before, then I changed SETTINGS_FLAVOUR to dev from local ,It worked, Its not working again.Do any of you know what's going wrong?

**Comment by kwk** [comment]
Hi @vchedeti, thank you for reporting your issue. Please, let me know which revision you're running (look at the bottom of the frontend). What does your topology look like and how did you start the frontend container (which parameters)? What version of the docker registry are you running (0.9.1 or v2)?

**Comment by vchedeti** [comment]
@kwk   This is git revision: b0743af and I'm using the v1 registry. I think delete is not working because registry stores all the images in v1/images directory. if two or more images refer to same image DELETE is not working. Please fix this if this the issue.

**Comment by vchedeti** [comment]
storage: 
  image: busybox 
  volumes: 
    - /var/lib/docker/registry
  command: true
cache: 
  image: redis
backend:
  image: registry 
  ports: 
    - xxx.xx.xx.xx:5000:5000
  links: 
    - cache 
    - storage 
  volumes: 
    - /registry:/var/lib/docker/registry
  environment: 
    SETTINGS_FLAVOR: dev 
    STORAGE_PATH: /var/lib/docker/registry
    SEARCH_BACKEND: sqlalchemy 
    CACHE_REDIS_HOST: cache 
    CACHE_REDIS_PORT: 6379 
    CACHE_LRU_REDIS_HOST: cache 
    CACHE_LRU_REDIS_PORT: 6379
   

frontend:
  image: konradkleine/docker-registry-frontend  
  ports:
   - 127.0.0.1:8081:80
  
  environment: 
    ENV_DOCKER_REGISTRY_HOST: xxx.xx.xx.xx
    ENV_DOCKER_REGISTRY_PORT: 5000

**Comment by kwk** [comment]
> I think delete is not working because registry stores all the images in v1/images directory. if two or more images refer to same image DELETE is not working.

Hi @vchedeti . Beware, that deleting a **tag** is not the same as deleting an **image**. Only once no tag refers to an image, it is safe to delete the image. I suggest, you read my [anwser on stackoverflow](http://stackoverflow.com/questions/25436742/deleting-images-from-a-private-docker-registry/25551160#25551160) for an explanation why this is and how you can semi-automate the actual deletion of images in your registry.

> Please fix this if this the issue.

I'm sorry to disappoint you @vchedeti but I cannot fix this as it is beyond the [Docker API](https://docs.docker.com/reference/api/registry_api/#delete-a-repository-tag) boundary of deleting a  tag.

Please, confirm that I understood you correctly and let me know if I can close this issue.

Here's a nice tip for your **.yml** file: If you add a `links` section to the frontend configuration you can  point to the registry by name instead of IP (` ENV_DOCKER_REGISTRY_HOST: registry`)

```yml
frontend:
  image: konradkleine/docker-registry-frontend  
  ports:
   - 127.0.0.1:8081:80
  links:
    - registry:registry
  environment: 
    ENV_DOCKER_REGISTRY_HOST: registry
    ENV_DOCKER_REGISTRY_PORT: 5000
```

**Comment by vchedeti** [comment]
Ok, I want to delete whole image including all the tags. why is this not working?? It worked before.

**Comment by kwk** [comment]
@vchedeti Please check the apache logs in `/var/log/apache2/error.log` to find out more and reopen this issue when there's news.
