### ISSUE TITLE
Redirect to /home everytime I try browse some repository

### ISSUE THREAD

**Issue by mcortinas** [kwk/docker-registry-frontend#72]
Hi, 

I'm running oficial docker repository from image (1e847b14150e365a95d76a9cc6b71cd67ca89905e3a0400fa44381ecf00890e1) and everytime I run the docker ui with this prompt command:

```
docker run \
        -d \
        -e ENV_DOCKER_REGISTRY_HOST=example.com \
        -e ENV_DOCKER_REGISTRY_PORT=5000 \
        -e ENV_DOCKER_REGISTRY_USE_SSL=1 \
        -e ENV_USE_SSL=yes \
        -e ENV_REGISTRY_PROXY_FQDN=example.com \
        -e ENV_REGISTRY_PROXY_PORT=443 \
        -v /opt/docker/certs/example.com.crt:/etc/apache2/server.crt:ro \
        -v /opt/docker/certs/example.com.key:/etc/apache2/server.key:ro \
        -p 443:443 \
        konradkleine/docker-registry-frontend:v2
```

The imageID from docker-registry-frontend:v2 is edc3baa902034c86d13ca5f751db6ed15515197e9ef84867f6e18f613bfac826
My problem lives in each time I try to request some particular repository (https://example.com/repository/centos), my browser loads the URI "https://example.com/home"

**Comment by itsypkin** [comment]
I faced the same issue

docker ui prompt command: 

```
sudo docker run \
  -d \
  -e ENV_DOCKER_REGISTRY_HOST=foo.bar.com \
  -e ENV_DOCKER_REGISTRY_PORT=5000 \
  -p 8080:80 \
  konradkleine/docker-registry-frontend:v2
```

docker-registry-frontend git revision is 4fe173e

**Comment by kwk** [comment]
Please consult https://github.com/kwk/docker-registry-frontend/tree/v2/example-setup to get help on how to setup a registry v2 with the frontend.

**Comment by itsypkin** [comment]
To be honest I'm not really sure that the problem is in configuration. Correct me if I'm wrong.

On the repositories list page the link for some image is set like http://my.registry.com/repository/repoName But looks like it doesn't satisfy any of router rules from https://github.com/kwk/docker-registry-frontend/blob/v2/app/app.js#L63 (That's why I've got redirected to home page) 

Based on this router settings the link to the page with the container details should look like `/repository/:repositoryUser/:repositoryName`. And when I try to open this page directly it works.

Could you please point me what can be wrong in my setup?  And why should I have something like registryUser? 

Thanks in advance

**Comment by kwk** [comment]
@jhony-chikens Currently the docker-registry-frontend can only work with images that are tagged in the form `namespace/image:tag`. Do you follow this naming scheme? Can you confirm your behaviour when using the example-setup that I've pointed you before?

**Comment by itsypkin** [comment]
@kwk with the example-setup the behavior is exactly the same

I follow the standard naming convention for private docker registries 
for instance:

```
docker tag debian:jessie myregistry.com:5000/debian:jessie
docker push myregistry.com:5000/debian:jessie
```

**Comment by kwk** [comment]
@jhony-chikens That is not standard convention. You miss the `namespace` portion. It should be something like 

```
docker tag debian:jessie myregistry.com:5000/official/debian:jessie
docker push myregistry.com:5000/official/debian:jessie
```

 Please test again.

**Comment by itsypkin** [comment]
@kwk yep now it works... Thank you a lot!
